
# SERVER CONFIGURATION
server:
  port: 8080

# MAIN SPRING CONFIGURATION
spring:
  # Turn off the Spring Boot startup banner (logo)
  main:
    banner-mode: off

  # APPLICATION CONFIGURATION
  application:
    name: SportsCenter

  # DATABASE CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3307/sportscenter
    username: root
    password: root

  # JPA & HIBERNATE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

# LOGGING CONFIGURATION
logging:
  level:
    # Sets the logging level for the entire application.
    # Only messages logged at ERROR or higher will be shown.
    # Options: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    root: ERROR